#include "os_firstinc.h"
#include "os_main.h"

#define SYS_HANDLER_CTRL_STATE_REG ((uint32*)0xE000ED24)
#define SYS_HANDLER_CTRL_STATE_BIT_MASK_USGFAULTENA ((uint32)0x00040000)
#define SYS_HANDLER_CTRL_STATE_BIT_MASK_BUSFAULTENA ((uint32)0x00020000)
#define SYS_HANDLER_CTRL_STATE_BIT_MASK_MEMFAULTENA ((uint32)0x00010000)
#define SYS_HANDLER_CTRL_STATE_ENA_ALL_EXCEP (*SYS_HANDLER_CTRL_STATE_REG = *SYS_HANDLER_CTRL_STATE_REG | SYS_HANDLER_CTRL_STATE_BIT_MASK_USGFAULTENA | SYS_HANDLER_CTRL_STATE_BIT_MASK_BUSFAULTENA | SYS_HANDLER_CTRL_STATE_BIT_MASK_MEMFAULTENA)

void OS_START_OS(void)
{
   /* activate all exception to improve the debug capabilities */
#if(CFG_PROCESSOR == cMCU_CORTEX_M4)
   SYS_HANDLER_CTRL_STATE_ENA_ALL_EXCEP;
#endif
   /* triggers hw & sw init (OS parts), interrupt system init (including MMU) */
   OS_STATE_HANDLER();
}
